#!/usr/bin/env bash

VERBOSE=0
RED=0
BLUE=0
GREEN=0
ALPHA=0
LIMIT=0
INVERT=0
declare INITIAL

trace() {
  [[ "$VERBOSE" == "1" ]] && {
    echo -e " \\033[96m--> \\033[97m$*\\033[39m"
  }
}

die() {
  echo "${1:-usage : ${0##*/} [ options ] }" 2>&1
  [ "$1" ] && exit 1
  cat > /dev/stdout <<EOF
  adjust hex color values

  options:
    -h | --help           show help
    --verbose             verbose output
    -l | --limit          limit color output from wrapping around
    -r | --red <value>    modify red by <value>
    -g | --green <value>  modify green by <value>
    -b | --blue <value>   modify blue by <value>
    -a | --alpha <value>  modify alpha by <value>
    -v | --invert         invert the would-be output (this operates after other modifications)
EOF
  exit 0
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h|--help)
      die
      ;;
    -l|--limit)
      LIMIT=1
      ;;
    --verbose)
      VERBOSE=1
      ;;
    -r|--red)
      RED="$2"
      shift
      ;;
    -g|--green)
      GREEN="$2"
      shift
      ;;
    -b|--blue)
      BLUE="$2"
      shift
      ;;
    -a|--alpha)
      ALPHA="$2"
      shift
      ;;
    -v|--invert)
      INVERT=1
      ;;
    *)
      INITIAL="$1"
      ;;
  esac
  shift
done

trace "Using options:"
trace "LIMIT: $LIMIT"
trace "INVERT: $INVERT"
trace "INITIAL: $INITIAL"
trace "RED: $RED"
trace "BLUE: $BLUE"
trace "GREEN: $GREEN"
trace "ALPHA: $ALPHA"

#
hex_arithmetic() {
  : "${INITIAL/\#}"
  # Break up into RGBA
  ((r=16#${_:0:2},g=16#${_:2:2},b=16#${_:4:2},a=16#${_:6:2}))

  # Do math
  [ "$LIMIT" == "1" ] && {
    r=$(printf "0x%02X" $(("$r" + 0x"$RED")))
    g=$(printf "0x%02X" $(("$g" + 0x"$BLUE")))
    b=$(printf "0x%02X" $(("$b" + 0x"$GREEN")))
    a=$(printf "0x%02X" $(("$a" + 0x"$ALPHA")))
    if [ ${#r} -gt 4 ]; then
      r="0xFF"
    fi
    if [ ${#g} -gt 4 ]; then
      g="0xFF"
    fi
    if [ ${#b} -gt 4 ]; then
      b="0xFF"
    fi
    if [ ${#a} -gt 4 ]; then
      a="0xFF"
    fi
  } || {
    r=$(printf "0x%02X" $(( $(("$r" + 0x"$RED"))   % "0x100")))
    g=$(printf "0x%02X" $(( $(("$g" + 0x"$GREEN")) % "0x100")))
    b=$(printf "0x%02X" $(( $(("$b" + 0x"$BLUE"))  % "0x100")))
    a=$(printf "0x%02X" $(( $(("$a" + 0x"$ALPHA")) % "0x100")))
  }

  # Print final output
  echo "#${r/0x}${g/0x}${b/0x}${a/0x}"
}

invert() {
  color="${1:?}"
  SHIFT_AMT=128
  inter=$(("$color" - "$SHIFT_AMT"))
  inter=$(("$inter" * -1))
  printf "%02X" $(("$inter" + "$SHIFT_AMT" - 1))
}

# Invert each of the RGB values - this does not operate on αlpha
hex_inversion() {
  local initial=${1/\#}
  # Break up into RGBA
  ((r=16#${initial:0:2},g=16#${initial:2:2},b=16#${initial:4:2},a=16#${initial:6:2}))
  r=$(invert "$r")
  g=$(invert "$g")
  b=$(invert "$b")
  a=$(printf "%02X" "$a")

  # Print final output
  echo "#${r}${g}${b}${a}"
}

output=$(hex_arithmetic)

trace "hex arithmetic output : $output"

[ "$INVERT" == 1 ] && hex_inversion "$output" || echo "$output"
